feature/add_topics
garipovroma/english-teacher-bot pull request #6
Opened 2024-05-01 11:50 UTC by garipovroma

2024-05-01 17:53 UTC, AdvancerMan requested changes

2024-05-01 17:53 UTC, AdvancerMan commented on topics.csv
> +26,Basics of "can", "could" and "be able to" (Ability and possibility),Modals
если в столбиках есть запятые, лучше столбики в кавычки оборачивать + внутренние кавычки экранировать, а то парсер может не съесть такое

сделать типа такого
```
26,"Basics of ""can"", ""could"" and ""be able to"" (Ability and possibility)",Modals
```

2024-05-01 18:07 UTC, AdvancerMan commented
обнови еще плиз scripts/fill_db.py чтобы он данные из этого файлика брал

2024-05-01 18:08 UTC, AdvancerMan requested changes
обнови еще плиз scripts/fill_db.py чтобы он данные из topics.csv брал

2024-05-02 15:13 UTC, garipovroma commented on topics.csv
> +26,Basics of "can", "could" and "be able to" (Ability and possibility),Modals
fixed

2024-05-02 16:56 UTC, AdvancerMan approved these changes
кааайф

2024-05-02 16:57 UTC, merged