Add exercise-assessment cycle
garipovroma/english-teacher-bot pull request #8
Opened 2024-05-18 14:25 UTC by AdvancerMan

2024-05-18 18:52 UTC, garipovroma commented
Добавь пожалуйста тест на кейс, когда пользователь вводит не число в качестве темы, у нас же под это отдельный иф

2024-05-19 11:07 UTC, ST-1580 requested changes

2024-05-19 11:07 UTC, ST-1580 commented on handlers/handlers.py
> +    logger.info(f"Received /start command from {user.name} in chat {chat.id}")
```chat.id``` можно добавить и во все остальные логи, не только в этот

2024-05-19 11:07 UTC, ST-1580 commented on tests/test_handlers.py
> +            message=create_text_message(telegram_application, message_id=2, text="42"),
Предлагаю еще проверить, когда пользователь вводит не число в качестве темы, у нас же под это отдельный ```if```

2024-05-19 11:18 UTC, garipovroma requested changes
нужно добавить тест, а так норм

2024-05-19 13:03 UTC, ST-1580 approved these changes

2024-05-19 14:05 UTC, garipovroma approved these changes

2024-05-19 14:09 UTC, merged